import type {Metadata} from "next";
import "./globals.css";
import {fonts} from "./fonts";
import {AuthProvider} from "@/providers/AuthProvider";

export const metadata: Metadata = {
    title: "Task Hive",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={fonts.inter.variable}>
        <body>
        <AuthProvider>
            {children}
        </AuthProvider>
        </body>
        </html>
    );
}
